//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.Manager.Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File.Manager.Resources.Enums.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abort.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Abort {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ask for decision.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Ask {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignore.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Ignore {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overwrite without asking.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Overwrite {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rename copied file.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Rename {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip.
        /// </summary>
        public static string GenericCopyMoveProblemResolution_Skip {
            get {
                return ResourceManager.GetString("GenericCopyMoveProblemResolution_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abort.
        /// </summary>
        public static string GenericDeleteProblemResolution_Abort {
            get {
                return ResourceManager.GetString("GenericDeleteProblemResolution_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ask.
        /// </summary>
        public static string GenericDeleteProblemResolution_Ask {
            get {
                return ResourceManager.GetString("GenericDeleteProblemResolution_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string GenericDeleteProblemResolution_Delete {
            get {
                return ResourceManager.GetString("GenericDeleteProblemResolution_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip.
        /// </summary>
        public static string GenericDeleteProblemResolution_Skip {
            get {
                return ResourceManager.GetString("GenericDeleteProblemResolution_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abort.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_Abort {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignore.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_Ignore {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignore all.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_IgnoreAll {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overwrite.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_Overwrite {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overwrite all.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_OverwriteAll {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_OverwriteAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rename.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_Rename {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rename all.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_RenameAll {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_RenameAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_Skip {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip all.
        /// </summary>
        public static string SingleCopyMoveProblemResolution_SkipAll {
            get {
                return ResourceManager.GetString("SingleCopyMoveProblemResolution_SkipAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abort.
        /// </summary>
        public static string SingleDeleteProblemResolution_Abort {
            get {
                return ResourceManager.GetString("SingleDeleteProblemResolution_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string SingleDeleteProblemResolution_Delete {
            get {
                return ResourceManager.GetString("SingleDeleteProblemResolution_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete all.
        /// </summary>
        public static string SingleDeleteProblemResolution_DeleteAll {
            get {
                return ResourceManager.GetString("SingleDeleteProblemResolution_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip.
        /// </summary>
        public static string SingleDeleteProblemResolution_Skip {
            get {
                return ResourceManager.GetString("SingleDeleteProblemResolution_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skip all.
        /// </summary>
        public static string SingleDeleteProblemResolution_SkipAll {
            get {
                return ResourceManager.GetString("SingleDeleteProblemResolution_SkipAll", resourceCulture);
            }
        }
    }
}
