//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.Manager.Resources.Modules.Filesystem.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File.Manager.Resources.Modules.Filesystem.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file {0}: {1}.
        /// </summary>
        public static string Error_CannotOpenFile {
            get {
                return ResourceManager.GetString("Error_CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to navigate to address {0}: {1}.
        /// </summary>
        public static string Error_FailedToNavigateToAddress {
            get {
                return ResourceManager.GetString("Error_FailedToNavigateToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain local drive list: {0}.
        /// </summary>
        public static string Error_FailedToObtainDriveList {
            get {
                return ResourceManager.GetString("Error_FailedToObtainDriveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} does not exist!.
        /// </summary>
        public static string Error_PathDoesNotExist {
            get {
                return ResourceManager.GetString("Error_PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SUB-DIR].
        /// </summary>
        public static string SizeDisplay_Directory {
            get {
                return ResourceManager.GetString("SizeDisplay_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DRIVE].
        /// </summary>
        public static string SizeDisplay_Drive {
            get {
                return ResourceManager.GetString("SizeDisplay_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UP-DIR].
        /// </summary>
        public static string SizeDisplay_UpDirectory {
            get {
                return ResourceManager.GetString("SizeDisplay_UpDirectory", resourceCulture);
            }
        }
    }
}
