//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File.Manager.Resources.Operations {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File.Manager.Resources.Operations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to return to parent folder from location {0}..
        /// </summary>
        public static string CopyMove_Critical_CannotExitDestinationFolder {
            get {
                return ResourceManager.GetString("CopyMove_Critical_CannotExitDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to return to parent folder from location {0}..
        /// </summary>
        public static string CopyMove_Critical_CannotExitSourceFolder {
            get {
                return ResourceManager.GetString("CopyMove_Critical_CannotExitSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copied files: {0} ({1}). Elapsed: {2}{3}.
        /// </summary>
        public static string CopyMove_Info_PartialDescription {
            get {
                return ResourceManager.GetString("CopyMove_Info_PartialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copied files: {0} / {1} ({2} / {3}). Elapsed: {4}, left: {5}{6}.
        /// </summary>
        public static string CopyMove_Info_TotalDescription {
            get {
                return ResourceManager.GetString("CopyMove_Info_TotalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot get attributes of file {2} in location {0}..
        /// </summary>
        public static string CopyMove_Question_CannotGetSourceFileAttributes {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotGetSourceFileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot get attributes of file {2} in location {1}..
        /// </summary>
        public static string CopyMove_Question_CannotGetTargetFileAttributes {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotGetTargetFileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot list source folder contents: {0}.
        /// </summary>
        public static string CopyMove_Question_CannotListSourceFolder {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotListSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot open destination file {2} in location {0}..
        /// </summary>
        public static string CopyMove_Question_CannotOpenDestinationFile {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotOpenDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot open source file {2} in location {0}..
        /// </summary>
        public static string CopyMove_Question_CannotOpenSourceFile {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotOpenSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot set attributes of file {2} in location {1}..
        /// </summary>
        public static string CopyMove_Question_CannotSetTargetFileAttributes {
            get {
                return ResourceManager.GetString("CopyMove_Question_CannotSetTargetFileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Destination file {2} already exists in location {1}..
        /// </summary>
        public static string CopyMove_Question_DestinationFileAlreadyExists {
            get {
                return ResourceManager.GetString("CopyMove_Question_DestinationFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Destination file {2} is read only..
        /// </summary>
        public static string CopyMove_Question_DestinationFileIsReadOnly {
            get {
                return ResourceManager.GetString("CopyMove_Question_DestinationFileIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Destination file {2} is a system file..
        /// </summary>
        public static string CopyMove_Question_DestinationFileIsSystem {
            get {
                return ResourceManager.GetString("CopyMove_Question_DestinationFileIsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to change attributes of the destination file {2}..
        /// </summary>
        public static string CopyMove_Question_FailedToChangeFileAttributes {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToChangeFileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to copy file {0} from {1} to {2}..
        /// </summary>
        public static string CopyMove_Question_FailedToCopyFile {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to create folder {2} in location {1}..
        /// </summary>
        public static string CopyMove_Question_FailedToCreateDestinationFolder {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToCreateDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open folder {2} in location {1}..
        /// </summary>
        public static string CopyMove_Question_FailedToEnterDestinationFolder {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToEnterDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open folde {2} in location {0}..
        /// </summary>
        public static string CopyMove_Question_FailedToEnterSourceFolder {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToEnterSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to delete source file {0} from location {1}..
        /// </summary>
        public static string CopyMove_Question_FailedToRemoveSourceFile {
            get {
                return ResourceManager.GetString("CopyMove_Question_FailedToRemoveSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Renamed file name {2} is invalid..
        /// </summary>
        public static string CopyMove_Question_InvalidRenamedFilename {
            get {
                return ResourceManager.GetString("CopyMove_Question_InvalidRenamedFilename", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Source file {2} does not exist in location {0}..
        /// </summary>
        public static string CopyMove_Question_SourceFileDoesNotExist {
            get {
                return ResourceManager.GetString("CopyMove_Question_SourceFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copying files.
        /// </summary>
        public static string CopyMove_Title_CopyingFiles {
            get {
                return ResourceManager.GetString("CopyMove_Title_CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Moving files.
        /// </summary>
        public static string CopyMove_Title_MovingFiles {
            get {
                return ResourceManager.GetString("CopyMove_Title_MovingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You can&apos;t copy items to the same location!.
        /// </summary>
        public static string CopyMove_Warning_CannotCopyItemsToTheSameLocation {
            get {
                return ResourceManager.GetString("CopyMove_Warning_CannotCopyItemsToTheSameLocation", resourceCulture);
            }
        }
    }
}
